# Generated by Django 3.0.7 on 2020-11-18 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiscord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=25, unique=True)),
                ('discord_id', models.CharField(max_length=25, unique=True)),
                ('faction', models.CharField(max_length=25)),
                ('region', models.CharField(max_length=25)),
            ],
        ),
    ]
